### PR TITLE
fix: import the type InjectionKey from vue3 in jsdoc

### LINKED ISSUE #18: Bug: should import type of `InjectionKey`
### Description
the type `InjectionKey` from `vue3` is including with the wrong way.
### Screenshots
<a href="https://ibb.co/N934g5C"></a>

### PR DESCRIPTION
**Pull request by devRickyyy**
Fix: https://github.com/casdoor/casdoor-vue-sdk/issues/18

### CODE REVIEW

**Comment by hsluoyz** [comment]
@leo220yuyaodog @jakiuncle plz review

**Comment by leo220yuyaodog** [comment]
Can you provider a release package for us to test? Now the sdk works well, after modifing, I can not confirm if it will work well.

**Comment by devRickyyy** [comment]
> Can you provider a release package for us to test? Now the sdk works well, after modifing, I can not confirm if it will work well.

Hello, here is the release package of this PR:

https://www.mediafire.com/file/628qe758scpv3dz/casdoor-vue-sdk-1.2.0.tgz/file

**Comment by jakiuncle** [comment]
In a vue project,it is no problem

**Comment by devRickyyy** [comment]
> Can you provider a release package for us to test? Now the sdk works well, after modifing, I can not confirm if it will work well.

I have tested this PR with `vue+ts` and `vue+js` projects (under Nodev16.17.0) and pack these here:

https://www.mediafire.com/file/me15fir460qjxkl/example.tar.gz/file

**Comment by leo220yuyaodog** [comment]
Ok,  I test fine too.

**Pull request merged**
